# Generated by Django 5.0.1 on 2024-02-10 10:29

import django.db.models.deletion
import marflix.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('age_rating', models.CharField(max_length=255)),
                ('synopsis', models.TextField(max_length=255)),
                ('release_year', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField()),
                ('average_rating', models.FloatField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('poster', models.ImageField(default='images/posters/default.png', upload_to='images/posters/')),
                ('cover', models.ImageField(default='images/covers/default.png', upload_to='images/covers/')),
                ('media', models.FileField(upload_to='videos/', validators=[marflix.validators.validate_video_extension])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
